// 画面・記録・トーストの文言 (日本語と英語)。値だけを置き、処理は書かない。
// {名前} は埋め込む値。名前・説明文 (敵・装備・スキルなど) は config/content.ts に置く。

const ja = {
  // タブ
  'tab.status': 'ステータス',
  'tab.tree': '強化',
  'tab.skill': 'スキル',
  'tab.relic': '遺物',
  'tab.equipment': '装備',
  'tab.inventory': 'インベントリ',
  'tab.log': '記録',
  'tab.map': 'マップ',
  'tab.settings': '設定',

  // コマンド
  'command.description': '勇者のステータスとインベントリをペインで開きます',
  'command.opened': 'Agent Hero のペインを開きました。',
  'pane.loading': '冒険の記録を読み込んでいます…',

  // 帯
  'band.reviving': '復活中…',
  'band.stairs': '階段を降りています',
  'band.door': '次の部屋へ',
  'band.working': '探索中',
  'band.resting': '休憩中',
  'band.farming': '周回',
  'band.power': 'PWR',

  // ステータス
  'status.hp': 'HP',
  'status.atk': '攻撃力',
  'status.def': '防御力',
  'status.tokenMultiplier': 'トークン倍率',
  'status.tokenMultiplierNote': '(強化のページが 1 つ開くごとに {mult} 倍)',
  'status.power': 'PWR',
  'status.powerNote': '(強化に使った memory の累計)',
  'status.skills': 'スキル',
  'status.noSkills': 'セットなし',
  'status.location': '現在地',
  'status.floor': '{dungeon} 地下 {floor} 階 (最深 {max} 階)',
  'status.kills': '討伐数',
  'status.killsDeaths': '{kills}  /  死亡 {deaths}',
  'status.tokens': '使用トークン {tokens} ({per} トークンで 1 {memory} × 倍率 {mult})',
  'status.totals': '強化の合計 (取得 {count} ノード)',
  'status.noTotals': 'まだ何も取得していません',

  // 強化
  'tree.allocatedCount': '取得済み {count}',
  'tree.title': 'T{tier} のツリー',
  'tree.nextCost': '次の取得',
  'tree.legend': 'o 小ノード  O 主要ノード  X キーストーン  白 = 取得できる',
  'tree.take': '取得',
  'tree.keystoneMark': '[キーストーン] ',
  'tree.size.start': '起点',
  'tree.size.small': '小ノード',
  'tree.size.notable': '主要ノード',
  'tree.size.keystone': 'キーストーン',
  'tree.size.point': 'SP ノード',
  'tree.state.allocated': '取得済み',
  'tree.state.available': '取得できる',
  'tree.state.locked': 'まだ取れない',
  'tree.state.blocked': '取得済み (先のノードを外すと払い戻せます)',
  'tree.origin': '盤面の起点',
  'tree.nextLevel': '次の Lv: {text}  Enter で上げます ({cost} memory)',
  'tree.help': '↑ ↓ ← → ノードを移動  Enter 取得 / Lv 上げ  Backspace 戻す  (盤面をクリックすると操作できます)',
  'tree.locked': 'T{tier} のページは、それより前のすべてのページでキーストーンを取ると新しくノードを取れます (足りないもの: {missing})',
  'tree.spNode': 'スキルポイント +1',

  // スキル
  'skill.header': 'セット中 {equipped}/{slots}  習得 {learned}/{total}',
  'skill.earned': ' (強化で {sp} 獲得)',
  'skill.none': 'セット中のスキルなし',
  'skill.equippedList': 'セット中: {names}',
  'skill.state.equipped': 'セット中',
  'skill.state.learned': '習得済み',
  'skill.state.available': '習得できる',
  'skill.state.locked': 'まだ習得できない',
  'skill.action.equipped': 'Enter で外します',
  'skill.action.learned': 'Enter でセットします',
  'skill.action.available': 'Enter で習得します',
  'skill.action.locked': '隣のスキルを習得すると習得できます',
  'skill.learnCost': '習得 {cost} SP',
  'skill.nextLevel': '次の Lv: {text}  ',
  'skill.upgradeCost': '+ で強化 {cost} SP',
  'skill.full': 'セットできるのは {slots} つまでです。先にどれかを外してください',
  'skill.help': '↑ ↓ ← → スキルを移動  Enter 習得 / セット / 外す  + 強化  Backspace 戻す  (盤面をクリックすると操作できます)',
  'skill.legend': '@ セット中  o 習得済み (色付き) / 習得できる (白) / まだ (灰)',
  'skill.unequip': '外す',
  'skill.equip': 'セット',
  'skill.notYet': '  まだ   ',
  'skill.upgrade': '強化 {cost} SP',
  'skill.slotsNote': '戦闘で効くのはセットした {slots} つまでです。習得はいくつでもできます',

  // 遺物
  'relic.header': 'スロット {used}/{slots}  所持 {count}/{cap}',
  'relic.note': 'ボスがまれに落とします。付与の数はボスの階の Tier で決まり (T1 で {first} つ)、スロットは強化で開いたページの数 − 1 です',
  'relic.none': 'まだ遺物を持っていません',
  'relic.unequip': '外す',
  'relic.equip': '付ける',
  'relic.discard': '手放す',
  'relic.affixes': '付与 {count}/{max}',
  'relic.inactive': '  (スロットが足りず効いていません)',

  // 装備・インベントリ
  'equip.weapon': '武器',
  'equip.armor': '防具',
  'equip.none': 'なし',
  'equip.atk': '攻撃',
  'equip.def': '防御',
  'equip.forge': '鍛錬 {cost} {memory}',
  'equip.forgeNote': '品質が 1 段上がります (必ず成功します)',
  'equip.forgeMax': '品質が最高 (アルティメット) なので鍛錬できません',
  'inventory.salvageAll': '一括分解 {count} 個 → +{gain} {memory}',
  'inventory.salvageNote': '一括分解は、装備中 (E) 以外の武器・防具をすべて memory に変えます',
  'inventory.equip': '装備',

  // マップ
  'map.farming': '地下 {floor} 階を周回中',
  'map.auto': '自動攻略中 (地下 {floor} 階)',
  'map.deepest': '最深 地下 {floor} 階',
  'map.selected': '選択中 地下 {floor} 階  ',
  'map.legend': '黄色 今いる階  赤 ボスの階',
  'map.help': '↑ ↓ ← → 階を選ぶ  Enter この階を周回  a 自動攻略に戻す  (マップをクリックすると操作できます)',
  'map.backToAuto': '自動攻略に戻す',
  'map.bossRoom': '{boss}の間',

  // 設定
  'settings.language': '言語',
  'settings.section.language': '言語',
  'settings.section.notify': '通知',
  'settings.section.version': 'バージョン',
  'settings.section.terms': '利用規約',
  'settings.section.data': 'セーブデータ',
  'settings.notifyNote': 'チェックを付けた種類だけを通知に出します (初期値はアップデートだけオン)。記録タブには、設定によらず残ります',
  'settings.notifyAllOn': '[すべてオン]',
  'settings.notifyAllOff': '[すべてオフ]',
  'notify.floor': '新しい階',
  'notify.floorNote': 'はじめての階に着いたとき',
  'notify.boss': 'ボス',
  'notify.bossNote': 'ボスが待ち構えているとき、倒したとき',
  'notify.death': '倒されたとき',
  'notify.deathNote': '勇者が倒されたとき',
  'notify.loot': '装備と遺物',
  'notify.lootNote': '良い品質の装備・自動で持ち替えた装備・遺物を手に入れたとき',
  'notify.forge': '鍛錬',
  'notify.forgeNote': '鍛錬で品質が上がったとき',
  'notify.update': 'アップデート',
  'notify.updateNote': '新しい版が出たとき (帯の 3 行目の案内は出し続けます)',
  'settings.languageNote': '画面・記録・名前の言語です。すでに書かれた記録は、書いた時点の言語のままです',

  'settings.version': 'バージョン',
  'settings.latest': '最新は v{latest}',
  'settings.upToDate': '最新',
  'settings.updateSteps': '更新の手順',
  'settings.reset': 'セーブデータ',
  'settings.resetButton': 'セーブデータをリセットする',
  'settings.resetNote': '最初の言語選択からやり直します',
  'settings.resetWarning': '進行・強化・スキル・装備・遺物がすべて消えます。元のセーブはバックアップとして ~/.claude/agent-hero/ に残ります。',
  'settings.resetConfirm': 'リセットする',
  'settings.resetCancel': 'やめる',
  'settings.step1': '1. ! claude plugin update agent-hero',
  'settings.step1Note': '   公開されている最新の版を取り寄せて入れ替えます',
  'settings.step2': '2. /reload-plugins',
  'settings.step2Note': '   入れ替えた版を読み込みます。反映されないときは Claude Code を再起動してください',

  // はじめての起動
  'setup.prompt': '/agent-hero を入力して冒険を始めてください',
  'setup.chooseLanguage': '言語を選んでください',
  'setup.devTitle': 'これは開発版です',
  'setup.devUnstable': '動作が安定しないことがあります。',
  'setup.devProgress': 'アップデートで、進行状況が変わったり消えたりすることがあります。',
  'setup.dataTitle': 'このプラグインが Claude Code から読み取る情報',
  'setup.dataReads': '読み取るもの: モデルの応答ごとのトークン数 (入力・出力・キャッシュ)、ターンの開始と終了 (帯の「探索中」の表示に使います)',
  'setup.dataNotRead': '読み取らないもの: プロンプト、会話の内容、コード、ファイルの中身、ツールの実行内容です',
  'setup.dataStored': '保存先: ~/.claude/agent-hero/ (このマシンの中だけです)',
  'setup.dataSend': '外部への送信: しません。トークン数を含め、読み取った情報も進行もどこにも送信しません',
  'setup.dataNetwork': '通信: 6 時間に 1 回、GitHub から plugin.json を受信して、新しい版があるか確かめます (受信だけで、送信はしません)',
  'setup.ok': '利用規約に同意して始める',
  'terms.title': '利用規約',
  'terms.devTitle': '開発版について',
  'terms.licenseTitle': 'ライセンス',
  'terms.license': 'MIT License です。このプラグインは無保証で提供され、利用によって生じた損害について作者は責任を負いません',
  'setup.back': '言語を選び直す',

  // アップデート
  'update.available': 'アップデートがあります (v{current} → v{latest})',
  'update.how': '! claude plugin update agent-hero を実行してから /reload-plugins してください',

  // 記録とトースト
  'log.start': '冒険が始まりました',
  'log.nodeLevelUp': 'T{tier} {name} を Lv{level} に上げました',
  'log.nodeTaken': 'T{tier} {name} を取得しました',
  'log.nodeLevelDown': 'T{tier} {name} を Lv{level} に下げました (+{amount} {memory})',
  'log.nodeRefund': 'T{tier} {name} を払い戻しました (+{amount} {memory})',
  'log.salvage': '装備 {count} 個を分解しました (+{gain} {memory})',
  'log.forged': '{item} に鍛え上げました (-{cost} {memory})',
  'log.equipped': '{item} を装備しました',
  'log.farmStart': '地下 {floor} 階の周回を始めました',
  'log.autoStart': '自動攻略に戻しました (地下 {floor} 階から)',
  'log.picked': '{item} を拾いました',
  'log.farmAgain': '地下 {floor} 階をもう一周します',
  'log.descend': '地下 {floor} 階へ降りました',
  'log.cast': '{names} を発動しました',
  'log.undying': '不死身で踏みとどまりました',
  'log.heavy': '{monster} の強攻撃! {damage} ダメージを受けました',
  'log.defeated': '{monster} に倒されました。地下 {floor} 階の入口からやり直します',
  'log.killed': '{monster} を倒しました',
  'log.relicGot': '遺物「{name}」を手に入れました',
  'log.relicEquipped': '遺物「{name}」を付けました',
  'log.relicDiscarded': '遺物「{name}」を手放しました',
  'log.skillLearned': 'スキル「{name}」を習得しました (-{cost} SP)',
  'log.skillUpgraded': 'スキル「{name}」を Lv{level} に強化しました (-{cost} SP)',
  'log.skillDowngraded': 'スキル「{name}」を Lv{level} に下げました (+{amount} SP)',
  'log.skillForgotten': 'スキル「{name}」の習得を取り消しました (+{amount} SP)',
  'note.reached': '地下 {floor} 階に到達しました',
  'note.bossWaiting': '{boss} が待ち構えています! {title}',
  'note.defeated': '{monster} に倒されました',
  'note.bossKilled': '{monster} を討伐しました',
  'note.got': '{item} を手に入れました',
  'note.equipped': '{item} を装備しました',
  'note.forged': '🔨 鍛錬! {item}',
  'note.listSeparator': '・',

  // 強化の効果の説明
  'mod.atk': '攻撃力',
  'mod.def': '防御力',
  'mod.hp': '最大 HP',
  'mod.crit': '会心率 +{v}',
  'mod.lifesteal': '与えたダメージの {v} を回復',
  'mod.regen': '1 歩ごとに最大 HP の {v} 回復',
  'mod.noRegen': '歩いての回復なし',
  'mod.dropRate': '装備ドロップ率 +{v}',
  'mod.qualityUp': '品質が 1 段上がる確率 +{v}',
  'mod.luck': '品質を 2 回抽選して良い方を取る',
  'mod.bossDmg': 'ボスへのダメージ +{v}',
  'mod.powerHit': '{every} 回に 1 回の攻撃のダメージ +{v}',
  'mod.double': '{v} の確率で 2 回攻撃',
  'mod.execute': 'HP が {v} 以下の敵を倒す (ボス以外)',
  'mod.bleed': '攻撃のたびに敵の最大 HP の {v} を追加ダメージ',
  'mod.parry': '{v} の確率で敵の攻撃を受けない',
  'mod.will': 'HP {below} 未満のとき受けるダメージ -{v}',
  'mod.counter': '攻撃を受けたとき {v} の確率で攻撃力の {ratio} を返す',
  'mod.thorns': '受けたダメージの {v} を敵に返す',
  'mod.bulwark': 'ボスから受けるダメージ -{v}',
  'mod.firstaid': '敵を倒すたびに最大 HP の {v} 回復',
  'mod.desperate': 'HP {below} 以下のとき攻撃力 +{v}',
  'mod.undying': '1 階につき 1 回、倒されても HP 1 で踏みとどまる',
  'mod.smith': '鍛錬の効率 +{v} (費用がそのぶん安くなる)',
  'mod.salvager': '分解でもらえる memory +{v}',
  'mod.luckChance': '{v} の確率で品質を 2 回抽選',
  'mod.tokenMult': 'トークン倍率 +{v}',
  'mod.spBonus': 'スキルポイント +{v}',
}

export type TextKey = keyof typeof ja

const en: Record<TextKey, string> = {
  'tab.status': 'Status',
  'tab.tree': 'Upgrades',
  'tab.skill': 'Skills',
  'tab.relic': 'Relics',
  'tab.equipment': 'Gear',
  'tab.inventory': 'Inventory',
  'tab.log': 'Log',
  'tab.map': 'Map',
  'tab.settings': 'Settings',

  'command.description': "Open a pane with the hero's status and inventory",
  'command.opened': 'Opened the Agent Hero pane.',
  'pane.loading': 'Loading the adventure…',

  'band.reviving': 'Reviving…',
  'band.stairs': 'Going downstairs',
  'band.door': 'Next room',
  'band.working': 'Exploring',
  'band.resting': 'Resting',
  'band.farming': 'Farming',
  'band.power': 'PWR',

  'status.hp': 'HP',
  'status.atk': 'Attack',
  'status.def': 'Defense',
  'status.tokenMultiplier': 'Token multiplier',
  'status.tokenMultiplierNote': '(x{mult} for each upgrade page opened)',
  'status.power': 'PWR',
  'status.powerNote': '(total memory spent on upgrades)',
  'status.skills': 'Skills',
  'status.noSkills': 'None set',
  'status.location': 'Location',
  'status.floor': '{dungeon} B{floor}F (deepest B{max}F)',
  'status.kills': 'Kills',
  'status.killsDeaths': '{kills}  /  deaths {deaths}',
  'status.tokens': 'Tokens used {tokens} ({per} tokens = 1 {memory} x {mult})',
  'status.totals': 'Upgrade totals ({count} nodes)',
  'status.noTotals': 'Nothing taken yet',

  'tree.allocatedCount': 'Taken {count}',
  'tree.title': 'T{tier} tree',
  'tree.nextCost': 'Next',
  'tree.legend': 'o small  O notable  X keystone  white = available',
  'tree.take': 'Take',
  'tree.keystoneMark': '[Keystone] ',
  'tree.size.start': 'Origin',
  'tree.size.small': 'Small node',
  'tree.size.notable': 'Notable',
  'tree.size.keystone': 'Keystone',
  'tree.size.point': 'SP node',
  'tree.state.allocated': 'Taken',
  'tree.state.available': 'Available',
  'tree.state.locked': 'Locked',
  'tree.state.blocked': 'Taken (refund the nodes beyond it first)',
  'tree.origin': 'Start of the board',
  'tree.nextLevel': 'Next Lv: {text}  Enter to raise ({cost} memory)',
  'tree.help': '↑ ↓ ← → move  Enter take / level up  Backspace undo  (click the board to control it)',
  'tree.locked': 'New nodes on T{tier} need a keystone on every earlier page (missing: {missing})',
  'tree.spNode': 'Skill points +1',

  'skill.header': 'Set {equipped}/{slots}  Learned {learned}/{total}',
  'skill.earned': ' ({sp} earned from upgrades)',
  'skill.none': 'No skills set',
  'skill.equippedList': 'Set: {names}',
  'skill.state.equipped': 'Set',
  'skill.state.learned': 'Learned',
  'skill.state.available': 'Available',
  'skill.state.locked': 'Locked',
  'skill.action.equipped': 'Enter to unset',
  'skill.action.learned': 'Enter to set',
  'skill.action.available': 'Enter to learn',
  'skill.action.locked': 'Learn a neighbouring skill first',
  'skill.learnCost': 'Learn {cost} SP',
  'skill.nextLevel': 'Next Lv: {text}  ',
  'skill.upgradeCost': '+ to upgrade {cost} SP',
  'skill.full': 'Up to {slots} skills can be set. Unset one first',
  'skill.help': '↑ ↓ ← → move  Enter learn / set / unset  + upgrade  Backspace undo  (click the board to control it)',
  'skill.legend': '@ set  o learned (colored) / available (white) / locked (grey)',
  'skill.unequip': 'Unset',
  'skill.equip': 'Set',
  'skill.notYet': '  locked ',
  'skill.upgrade': 'Upgrade {cost} SP',
  'skill.slotsNote': 'Only the {slots} skills you set work in battle. You can learn as many as you like',

  'relic.header': 'Slots {used}/{slots}  Owned {count}/{cap}',
  'relic.note': 'Bosses rarely drop them. Affixes depend on the boss floor tier ({first} at T1). Slots = upgrade pages opened − 1',
  'relic.none': 'No relics yet',
  'relic.unequip': 'Remove',
  'relic.equip': 'Equip',
  'relic.discard': 'Discard',
  'relic.affixes': 'Affixes {count}/{max}',
  'relic.inactive': '  (no free slot, inactive)',

  'equip.weapon': 'Weapon',
  'equip.armor': 'Armor',
  'equip.none': 'none',
  'equip.atk': 'ATK',
  'equip.def': 'DEF',
  'equip.forge': 'Forge {cost} {memory}',
  'equip.forgeNote': 'Raises quality by one grade (always succeeds)',
  'equip.forgeMax': 'Already at the highest quality (Ultimate)',
  'inventory.salvageAll': 'Salvage all {count} → +{gain} {memory}',
  'inventory.salvageNote': 'Salvages every weapon and armor except the equipped ones (E) into memory',
  'inventory.equip': 'Equip',

  'map.farming': 'Farming B{floor}F',
  'map.auto': 'Auto exploring (B{floor}F)',
  'map.deepest': 'Deepest B{floor}F',
  'map.selected': 'Selected B{floor}F  ',
  'map.legend': 'yellow current floor  red boss floor',
  'map.help': '↑ ↓ ← → choose a floor  Enter farm this floor  a back to auto  (click the map to control it)',
  'map.backToAuto': 'Back to auto',
  'map.bossRoom': "{boss}'s Lair",

  'settings.language': 'Language',
  'settings.section.language': 'Language',
  'settings.section.notify': 'Notifications',
  'settings.section.version': 'Version',
  'settings.section.terms': 'Terms',
  'settings.section.data': 'Save data',
  'settings.notifyNote': 'Only checked kinds are shown as notifications (only Updates is on by default). Everything stays in the Log tab',
  'settings.notifyAllOn': '[All on]',
  'settings.notifyAllOff': '[All off]',
  'notify.floor': 'New floor',
  'notify.floorNote': 'When reaching a floor for the first time',
  'notify.boss': 'Bosses',
  'notify.bossNote': 'When a boss is waiting and when it is defeated',
  'notify.death': 'Defeated',
  'notify.deathNote': 'When the hero is defeated',
  'notify.loot': 'Gear and relics',
  'notify.lootNote': 'When getting high-quality gear, auto-equipped gear or a relic',
  'notify.forge': 'Forging',
  'notify.forgeNote': 'When forging raises the quality',
  'notify.update': 'Updates',
  'notify.updateNote': 'When a new version is out (the third band line stays)',
  'settings.languageNote': 'Language of the screens, log and names. Existing log lines stay in the language they were written in',

  'settings.version': 'Version',
  'settings.latest': 'latest is v{latest}',
  'settings.upToDate': 'up to date',
  'settings.updateSteps': 'How to update',
  'settings.reset': 'Save data',
  'settings.resetButton': 'Reset save data',
  'settings.resetNote': 'Start over from the language selection',
  'settings.resetWarning': 'Progress, upgrades, skills, gear and relics will all be erased. The old save is kept as a backup in ~/.claude/agent-hero/.',
  'settings.resetConfirm': 'Reset',
  'settings.resetCancel': 'Cancel',
  'settings.step1': '1. ! claude plugin update agent-hero',
  'settings.step1Note': '   Download the latest published version and install it',
  'settings.step2': '2. /reload-plugins',
  'settings.step2Note': '   Load the new version. If it does not take effect, restart Claude Code',

  'setup.prompt': 'Type /agent-hero to start the adventure',
  'setup.chooseLanguage': 'Choose a language',
  'setup.devTitle': 'This is a development version',
  'setup.devUnstable': 'It may not work reliably.',
  'setup.devProgress': 'Updates may change or erase your progress.',
  'setup.dataTitle': 'What this plugin reads from Claude Code',
  'setup.dataReads': 'Reads: token counts of each model response (input, output, cache) and when turns start and end (for the "Exploring" status)',
  'setup.dataNotRead': 'Does not read: prompts, conversations, code, file contents, or tool calls',
  'setup.dataStored': 'Stored in: ~/.claude/agent-hero/ (on this machine only)',
  'setup.dataSend': 'Sending: none. Nothing it reads, token counts included, and none of your progress is sent anywhere',
  'setup.dataNetwork': 'Network: every 6 hours, downloads plugin.json from GitHub to check for a new version (download only, nothing is uploaded)',
  'setup.ok': 'Agree to the terms and start',
  'terms.title': 'Terms of use',
  'terms.devTitle': 'Development version',
  'terms.licenseTitle': 'License',
  'terms.license': 'MIT License. This plugin is provided as is, without warranty, and the author is not liable for any damage from its use',
  'setup.back': 'Choose the language again',

  'update.available': 'An update is available (v{current} → v{latest})',
  'update.how': 'Run ! claude plugin update agent-hero, then /reload-plugins',

  'log.start': 'The adventure began',
  'log.nodeLevelUp': 'Raised T{tier} {name} to Lv{level}',
  'log.nodeTaken': 'Took T{tier} {name}',
  'log.nodeLevelDown': 'Lowered T{tier} {name} to Lv{level} (+{amount} {memory})',
  'log.nodeRefund': 'Refunded T{tier} {name} (+{amount} {memory})',
  'log.salvage': 'Salvaged {count} items (+{gain} {memory})',
  'log.forged': 'Forged into {item} (-{cost} {memory})',
  'log.equipped': 'Equipped {item}',
  'log.farmStart': 'Started farming B{floor}F',
  'log.autoStart': 'Back to auto exploring (from B{floor}F)',
  'log.picked': 'Picked up {item}',
  'log.farmAgain': 'Another round of B{floor}F',
  'log.descend': 'Went down to B{floor}F',
  'log.cast': 'Used {names}',
  'log.undying': 'Held on with Undying',
  'log.heavy': '{monster} heavy attack! {damage} damage',
  'log.defeated': 'Defeated by {monster}. Starting B{floor}F over',
  'log.killed': 'Defeated {monster}',
  'log.relicGot': 'Found the relic "{name}"',
  'log.relicEquipped': 'Equipped the relic "{name}"',
  'log.relicDiscarded': 'Discarded the relic "{name}"',
  'log.skillLearned': 'Learned "{name}" (-{cost} SP)',
  'log.skillUpgraded': 'Upgraded "{name}" to Lv{level} (-{cost} SP)',
  'log.skillDowngraded': 'Lowered "{name}" to Lv{level} (+{amount} SP)',
  'log.skillForgotten': 'Forgot "{name}" (+{amount} SP)',
  'note.reached': 'Reached B{floor}F',
  'note.bossWaiting': '{boss} awaits! {title}',
  'note.defeated': 'Defeated by {monster}',
  'note.bossKilled': 'Slew {monster}',
  'note.got': 'Got {item}',
  'note.equipped': 'Equipped {item}',
  'note.forged': '🔨 Forged! {item}',
  'note.listSeparator': ', ',

  'mod.atk': 'Attack',
  'mod.def': 'Defense',
  'mod.hp': 'Max HP',
  'mod.crit': 'Crit chance +{v}',
  'mod.lifesteal': 'Heal {v} of damage dealt',
  'mod.regen': 'Restore {v} of max HP per step',
  'mod.noRegen': 'No healing while walking',
  'mod.dropRate': 'Equipment drop rate +{v}',
  'mod.qualityUp': 'Chance of +1 quality grade +{v}',
  'mod.luck': 'Roll quality twice and keep the better',
  'mod.bossDmg': 'Damage to bosses +{v}',
  'mod.powerHit': 'Every {every}th attack deals +{v} damage',
  'mod.double': '{v} chance to attack twice',
  'mod.execute': 'Kill enemies at {v} HP or less (not bosses)',
  'mod.bleed': "Each hit deals {v} of the enemy's max HP as extra damage",
  'mod.parry': '{v} chance to avoid an attack',
  'mod.will': 'Below {below} HP, damage taken -{v}',
  'mod.counter': '{v} chance to return {ratio} of attack when hit',
  'mod.thorns': 'Return {v} of damage taken',
  'mod.bulwark': 'Damage from bosses -{v}',
  'mod.firstaid': 'Restore {v} of max HP per kill',
  'mod.desperate': 'At {below} HP or less, attack +{v}',
  'mod.undying': 'Once per floor, survive a lethal hit with 1 HP',
  'mod.smith': 'Forging efficiency +{v} (lower cost)',
  'mod.salvager': 'Salvage memory +{v}',
  'mod.luckChance': '{v} chance to roll quality twice',
  'mod.tokenMult': 'Token multiplier +{v}',
  'mod.spBonus': 'Skill points +{v}',
}

export const TEXT: Record<'ja' | 'en', Record<TextKey, string>> = { ja, en }
export const LANGUAGES = [
  { id: 'ja', name: '日本語' },
  { id: 'en', name: 'English' },
] as const
